name: cronicalia_flutter
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flushbar: ^0.9.2

  #firebase
  firebase_auth: "^0.5.20"
  cloud_firestore: "0.8.0"
  firebase_storage: "1.0.2"
  firebase_core: "^0.2.5"

  #login
  google_sign_in: "3.0.4"
  flutter_twitter_login: "1.1.0"
  flutter_facebook_login: "1.1.1"

  #image manipulation
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git

  #book files manipulation
  #ePub files
  epub: ^2.0.2
  flutter_full_pdf_viewer: ^1.0.1
  flutter_html: ^0.7.1

  validate: "1.6.1"
  flutter_flux: 
   git: https://github.com/google/flutter_flux
  path_provider: "0.4.1"
  image_picker: "0.4.6"

  flutter_document_picker: "1.1.1"
  html: ^0.13.3+3
  intl: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/horizon.png
     - images/unknown_profile_pic.png
     - images/poster_placeholder.png
     - images/cover_placeholder.png
     - images/empty_book_list_land.png
     - images/empty_book_list_port.png
     - images/book_background.png
     - images/icon_stub.png
     
     - assets/test_file.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
